{
 "title": "Hospital Observability Dashboard",
 "description": "........",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Patients",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(patients_number )", "legendFormat": "Total Patients" }
   ]
  },
  {
   "title": "Male Patients ",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(patients_male_number)", "legendFormat": "Male Patients " }
   ]
  },
  {
   "title": "Female Patients",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(patients_female_number)", "legendFormat": "Female Patients" }
   ]
  },
  {
   "title": "Doctors",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(doctors_number)", "legendFormat": "Doctors" }
   ]
  },
  {
   "title": "Nurses",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(nurses_number)", "legendFormat": "Nurses" }
   ]
  },
  {
   "title": "Receptionists",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(receptionists_number)", "legendFormat": "Receptionists" }
   ]
  },
  {
   "title": "Users",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(users_number)", "legendFormat": "Users" }
   ]
  },
  {
   "title": "Devices",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(devices_number)", "legendFormat": "Devices" }
   ]
  },
  {
   "title": "All Messages",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(messages_number)", "legendFormat": "All Messages" }
   ]
  },
  {
   "title": "All Conversations",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(conversations_number)", "legendFormat": "All Conversations" }
   ]
  },
  {
   "title": "All Readings",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(readings_number)", "legendFormat": "All Readings" }
   ]
  }
 ]
}